// Generated protobuf code
// This file would be generated by prost-build from proto/protosyte.proto
// For now, providing a simplified structure

pub mod protosyte {
    pub mod core {
        pub mod v2 {
            use prost_types::Timestamp;
            
            #[derive(Clone, PartialEq, prost::Message)]
            pub struct Envelope {
                #[prost(fixed64, tag = "1")]
                pub mission_id: u64,
                #[prost(message, optional, tag = "2")]
                pub collected_ts: Option<Timestamp>,
                #[prost(fixed32, tag = "3")]
                pub sequence: u32,
                #[prost(oneof = "envelope::Payload", tags = "4, 5, 6")]
                pub payload: Option<envelope::Payload>,
                #[prost(bytes, tag = "15")]
                pub hmac_sha256: Vec<u8>,
            }
            
            pub mod envelope {
                use super::super::super::{Heartbeat, DataBlob, Error};
                
                #[derive(Clone, PartialEq, prost::Oneof)]
                pub enum Payload {
                    #[prost(message, tag = "4")]
                    Heartbeat(Heartbeat),
                    #[prost(message, tag = "5")]
                    Data(DataBlob),
                    #[prost(message, tag = "6")]
                    Error(Error),
                }
            }
            
            #[derive(Clone, PartialEq, prost::Message)]
            pub struct Heartbeat {
                #[prost(float, tag = "1")]
                pub load_avg_1m: f32,
                #[prost(uint32, tag = "2")]
                pub mem_free_mb: u32,
                #[prost(string, repeated, tag = "3")]
                pub active_hooks: Vec<String>,
            }
            
            #[derive(Clone, PartialEq, prost::Message)]
            pub struct DataBlob {
                #[prost(bytes, tag = "1")]
                pub host_fingerprint: Vec<u8>,
                #[prost(enumeration = "DataType", tag = "2")]
                pub data_type: i32,
                #[prost(bytes, tag = "3")]
                pub encrypted_payload: Vec<u8>,
                #[prost(bytes, tag = "4")]
                pub aes_gcm_nonce: Vec<u8>,
                #[prost(uint32, tag = "5")]
                pub original_size: u32,
            }
            
            #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, prost::Enumeration)]
            #[repr(i32)]
            pub enum DataType {
                Unspecified = 0,
                CredentialBlob = 1,
                NetworkFlow = 2,
                FileMetadata = 3,
                ProcessInjection = 4,
                ConfigState = 5,
            }
            
            #[derive(Clone, PartialEq, prost::Message)]
            pub struct Error {
                #[prost(enumeration = "error::Severity", tag = "1")]
                pub severity: i32,
                #[prost(string, tag = "2")]
                pub context: String,
                #[prost(int32, tag = "3")]
                pub errno: i32,
            }
            
            pub mod error {
                #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, prost::Enumeration)]
        #[repr(i32)]
                pub enum Severity {
                    Unknown = 0,
                    HookFailure = 1,
                    BufferOverflow = 2,
                    ExfilDisabled = 3,
                }
            }
        }
    }
}

